### ISSUE TITLE
Customized options

### ISSUE THREAD

**Issue by jonathanwoahn** [fmaturel/angular-timelinejs3#1]
First off, this is awesome! Thanks for pulling it together.

Second, I don't see any way to import customized options for the timeline (i.e. if I want to customize the ratio of the timeline to the rest of the story, default zoom level, scale factors, etc.). Is this functionality there and I'm just blind, or is it not implemented?

**Comment by fmaturel** [comment]
You're right it's not (yet) implemented... I did not need this feature but It should not be too hard to add it.

**Comment by fmaturel** [comment]
Just added the feature in 0.0.3 :smiley: Hope you enjoy it!
