### ISSUE TITLE
ng-click

### ISSUE THREAD

**Issue by cmrenus** [fmaturel/angular-timelinejs3#8]
On a slide, I am trying to add an ng-click event to the headline for each event to execute a function. How can I do that? I have an <a> tag with the ng-click, but when I click the headline, non of it executes. Is it a scope issue?

**Comment by fmaturel** [comment]
Would you have some code exemples to see what you want to achieve?
thanks!

**Comment by cmrenus** [comment]
`text: {
						headline: "<a href='' ng-click='console.log(\"here\"); openEventDetails($event)'>" + data[x].name + "</a>",
						text: data[x].venue.name
					},`

This is where I am creating each slide object, and just looping through. The headline is clickable, just nothing happens. The console log doesnt happen and the function isn't reached either.

**Comment by cmrenus** [comment]
I figured it out. I had to pass $scope as a variable into the slide. Did not realize i could do that. Don't understand why console.log() would not work there though

**Comment by fmaturel** [comment]
Nice to see you finally did it!

**Comment by FarhanGhumra** [comment]
How to achieve same thing if I am not using `$scope` but [`controllerAs`](https://johnpapa.net/angularjss-controller-as-and-the-vm-variable/) pattern? 

[ui-grid](https://github.com/angular-ui/ui-grid) provides an option called [`appScopeProvider`](http://ui-grid.info/docs/#!/api/ui.grid.class:GridOptions), using that I can assign the parent controller scope.
